<?php
/**
 * @file
 * A block module that displays the pension calculator.
 */

/**
 * Implementation of hook_block_info().
 */

function naked_page_block_info() {
  $blocks['naked_page'] = array(
    'info' => t('Block to be included in naked landing pages to hide the navigation menus'),
  );
  return $blocks;
}


function naked_page_contents(){
  return "";
}

function naked_page_block_view($delta = '') {
  switch($delta) {
    case 'naked_page':
    $block['subject'] = t('');
    if (user_access('access content')) {

      $result = naked_page_contents();
      $block['content'] = $result;
      drupal_add_js(drupal_get_path('module', 'naked_page') .'/js/nakedPage.js', array('scope' => 'footer'));
    }
    return $block;
  }
 }


