<?php
/**
 * @file
 * A block module that displays the Claim Statistics Map Block
 */



/**
 * Implementation of hook_block_info().
 */

function claim_stats_map_block_info() {
  $blocks['claim_stats_map'] = array(
    'info' => t('Claim Statistics Map Block'),
  );
  return $blocks;
}

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */

function claim_stats_map_help($path, $arg) {
  switch ($path) {
    case "admin/help#claim_stats_map":
      return '<p>' . t("Displays links to nodes created on this date") . '</p>';
      break;
  }
}

/**
 * Custom content function.
 *
 * Set beginning and end dates, retrieve posts from database
 * saved in that time period.
 *
 * @return
 *   A result set of the targeted posts.
 */

function claim_stats_map_contents(){
  return '
<div class="hFirst">
  <div class="section leading vFirst noBg">
    <div id="map-holder">
      

      <div id="IL" class="IL">
        <div id="buttonHolder" class="buttonHolder"> </div>
        <div id="chart" class="chart">
          <div id="map" class="map"> </div>
        </div>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript"><!--

  var urlArray = window.location.pathname.split("/");
  var currentPage = urlArray[urlArray.length - 1];
  var r = /\d+/;
  var year = currentPage.match(r);

  var statCSV="/sites/retail/files/stats" + year +".csv";

//--></script>

';
}


function claim_stats_map_block_view($delta = '') {
  switch($delta) {
    case 'claim_stats_map':
    $block['subject'] = t('');
    if (user_access('access content')) {
      // Use our custom function to retrieve data
      $result = claim_stats_map_contents();
      // No content in the last week
      $block['content'] = $result;

      drupal_add_css(drupal_get_path('module', 'claim_stats_map') . '/css/claims-stats.css', array('group' => CSS_DEFAULT));


      drupal_add_js(drupal_get_path('module', 'claim_stats_map') .'/js/d3.v3.js', array('scope' => 'footer'));
      drupal_add_js(drupal_get_path('module', 'claim_stats_map') .'/js/loader.js', array('scope' => 'footer'));
      drupal_add_js(drupal_get_path('module', 'claim_stats_map') .'/js/bubbles.js', array('scope' => 'footer'));
      drupal_add_js(drupal_get_path('module', 'claim_stats_map') .'/js/makePie.js', array('scope' => 'footer'));
      drupal_add_js(drupal_get_path('module', 'claim_stats_map') .'/js/zoom.js', array('scope' => 'footer'));
      drupal_add_js(drupal_get_path('module', 'claim_stats_map') .'/js/main.js', array('scope' => 'footer'));
    }
    return $block;
  }
 }


