<?php
/**
 * @file
 * A block module that displays the pension calculator.
 */



/**
 * Implementation of hook_block_info().
 */

function callback_page_block_info() {
  $blocks['callback_page'] = array(
    'info' => t('callback Page Block'),
  );
  return $blocks;
}

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */

function callback_page_help($path, $arg) {
  switch ($path) {
    case "admin/help#callback_page":
      return '<p>' . t("Displays links to nodes created on this date") . '</p>';
      break;
  }
}

/**
 * Custom content function.
 *
 * Set beginning and end dates, retrieve posts from database
 * saved in that time period.
 *
 * @return
 *   A result set of the targeted posts.
 */
function callback_page_contents(){
  return '<div id="mainContent" class="blockContainer">
<div class="hFirst">
	<h2 class="callback-h2">Request a callback</h2>
  <div class="progressBox" style="margin-bottom: 20px">
    <div class="complyNote">
      <p>To talk to one of our qualified financial advisers use this call back form. Your personal details will only be used to deal with your request.  Before you give us your information please see our <a href="https://www.irishlife.ie/ilfs-privacy-notice">privacy notice</a>  for your rights and how your information is used.</p>  
	  <br/>
	  
	<br/>
    </div>
    <div id="progressBoxPopupContents">
	<form id="callback">
      <div class="progressInputs">
        <span>Your Name:</span><br>
		<input type="text" id="progressName" name="progressName" required><br>
        <span>Phone Number:</span><br>
		<input type="tel" id="progressPhone" name="progressPhone" pattern="[0-9A-Z]{|^\s*\(?\s*\d{1,4}\s*\)?\s*[\d\s]{5,10}\s*$|}" required><br>

        <span>Area of interest:</span><br>
        <select id="callbackAreaInterest" name="callbackAreaInterest">
          <option selected="selected" value=""></option>
          <option value="new plan">Looking for financial advice regarding a new plan</option>
          <option value="existing plan">Looking for advice relating to an existing Irish Life plan</option>
        </select>
        <br>

        <span>Best Time to call:</span><br>
        <select id="progressCalltime" name="calltime">
          <option value="NOW">Now</option>
          <option value="anytime" selected="selected">Anytime</option>
          <option value="morning-before-12pm">Morning (before 12pm)</option>
          <option value="afternoon-12pm-to-5pm">Afternoon (12pm to 5pm)</option>
          <option value="evening-5pm-to-8pm">Evening (5pm to 8pm)</option>
        </select>
		<br>
		
      <a id="sendAdvisorCallbackForm" class="progressButtons submitDetails " href="javascript:void(0);" style="display:none">Call me back</a>
      <a id="sendAdvisorCallbackForm2" class="progressButtons submitDetails " href="javascript:void(0);" style="display:none">Call me back</a>
	  <br>
	  <div class="complyNote"><p>In the interest of customer service, calls will be recorded and monitored.<br />
	  Callbacks are available Monday to Friday.</p></div>
      
	  </div>
      <br>

      <div class="progressSummary" style="display: none;">
        <span id="callbackAdvisorImg"><img alt="Advisor Callback" src="/sites/all/modules/css/images/advisor.callback-2.jpg"></span>
      </div>

      
	  </form>
  </div>

  <div class="clearer"></div><br>

  <div style="DISPLAY: none" id="loadingbox" class="loading"><img alt="Loading" src="/sites/all/modules/css/images/loading.gif"><h4>Loading, please wait</h4>
    <br><br><br><br><br></div>


  <div style="DISPLAY: none" id="loadingcomplete" class="middle">
    <h4>Your details have been sent and we will contact you soon.</h4>
    <br>
  </div>

  
</div>
<p>Irish Life Financial Services does not provide advice in relation to health insurance.<br>
Looking to buy health insurance from Irish Life Health, please <a href="https://www.irishlifehealth.ie/" target="_blank">click here</a> to find out more.</p>
</div>
<br>
<div class="clearer"></div>
</div>';
}

function callback_page_block_view($delta = '') {
  switch($delta) {
    case 'callback_page':
    $block['subject'] = t('');
    if (user_access('access content')) {
      // Use our custom function to retrieve data
      $result = callback_page_contents();
      // No content in the last week
      $block['content'] = $result;

      drupal_add_css(drupal_get_path('module', 'callback') . '/css/callback.css', array('group' => CSS_DEFAULT,'weight' => 100));

      drupal_add_js(drupal_get_path('module', 'javascript') .'/js/mk.js',array('scope' => 'footer'));
      drupal_add_js(drupal_get_path('module', 'callback_page') .'/js/callback_page.js',array('scope' => 'footer'));

    }
    return $block;
  }
 }


