<?php
/**
 * @file
 * A block module that displays the pension calculator.
 */


/**
 * Implementation of hook_block_info().
 */

/**
 * Implementation of hook_block_info().
 */
function javascript_block_info() {
  $blocks['javascript'] = array(
    'info' => t('Pension Calculator Block'),
  );
  return $blocks;
}

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */

function javascript_help($path, $arg) {
  switch ($path) {
    case "admin/help#javascript":
      return '<p>' . t("Displays links to nodes created on this date") . '</p>';
      break;
  }
}