<?php
/**
 * Implementation of hook_block_info().
 */
function pdf_download_list_block_info() {
  $blocks['pdf_download_list'] = array(
    'info' => t('PDF Download List'),
  );
  return $blocks;
}

 /**
 * Implementation of hook_block_permission().
 */
 
function pdf_download_list_permission() {
  return array(
    'pdf_download_list' => array(
      'title' => t('Administer PDF Download List'),
      'description' => t('Perform administration tasks for Fund Centre.'),
	  'restrict access' => true,
    ),
  );
}


function pdf_download_list_help($path, $arg) {
  switch ($path) {
    case "admin/help#pdf_download_list":
      return '<p>' . t("Displays links to nodes created on this date") . '</p>';
      break;
  }
}


/**
 * Implements hook_menu().
 */
function pdf_download_list_menu() {
  
 $items['admin/content/pdf_download_list'] = array(
    'title' => 'PDF Download List',
    'description' => 'Settings for Bline PDF Download List',
    'page callback' => array('drupal_get_form'),
    'page arguments' => array('pdf_download_list_admin'),
    'access arguments' => array('pdf_download_list'), // Those with this permission will be allowed to see the results	
    'type' => MENU_NORMAL_ITEM 
   );
   

  return $items;
}

function pdf_download_list_admin()
{
  $query = new EntityFieldQuery();
  $result = $query  ->entityCondition('entity_type', 'node')
          ->entityCondition('bundle', 'bline_document')
          ->execute();   
      	
            $entity_type = 'node';
            $result = $query->execute();

            if (!empty($result[$entity_type])) {
            $entities = entity_load($entity_type, array_keys($result[$entity_type]));
            }

            $nodes = entity_load('node', array_keys($result['node']));

  
		$stack = array();
  foreach ($nodes as $node) {
     	


		if (!empty($node->field_bline_file_uploaded[und][0][uri]) || strlen($node->field_bline_file_uploaded[und][0][uri])>=5) {

			$uriIn = $node->field_bline_file_uploaded[und][0][uri];
			$dir_uri = file_stream_wrapper_get_instance_by_uri($uriIn);
			$result = $dir_uri->getExternalUrl();
			$stack[t($result)] = t($node->title);
		}
  }
  
		asort($stack);
		
		$form ["pdf_download_list_popular_title"] = array(
	      '#type' => 'textfield',
	      '#title' => t("Title of section"),
	      '#default_value' => variable_get("pdf_download_list_popular_title","Popular PDFs"),
	      '#description' => t("Title of section"),
	      '#required' => FALSE,
		);
	
	
	
	
	   $form['pdf_download_list_first'] = array(
		   '#type' => 'select',
		   '#title' => t('1st on list'),
		   '#options' => $stack,
		   '#default_value' => variable_get('pdf_download_list_first')
	   );
		$form ["pdf_download_list_first_title"] = array(
	      '#type' => 'textfield',
	      '#title' => t("1st PDF title"),
	      '#default_value' => variable_get("pdf_download_list_first_title",""),
	      '#description' => t("1st PDF title"),
	      '#required' => FALSE,
		);
	   
	   
	   
	   $form['pdf_download_list_second'] = array(
		   '#type' => 'select',
		   '#title' => t('2nd on list'),
		   '#options' => $stack,
		   '#default_value' => variable_get('pdf_download_list_first'),
		   '#description' => t('2nd on list'),
	   );
	   
		$form ["pdf_download_list_second_title"] = array(
	      '#type' => 'textfield',
	      '#title' => t("2nd PDF title"),
	      '#default_value' => variable_get("pdf_download_list_second_title",""),
	      '#description' => t("2nd PDF title"),
	      '#required' => FALSE,
		);
		
		
	   $form['pdf_download_list_third'] = array(
		   '#type' => 'select',
		   '#title' => t('3rd on list'),
		   '#options' => $stack,
		   '#default_value' => variable_get('pdf_download_list_third'),
		   '#description' => t('3rd on list'),
	   );
	   
		$form ["pdf_download_list_third_title"] = array(
	      '#type' => 'textfield',
	      '#title' => t("3rd PDF title"),
	      '#default_value' => variable_get("pdf_download_list_third_title",""),
	      '#description' => t("3rd PDF title"),
	      '#required' => FALSE,
		);
		
		
		
	   $form['pdf_download_list_fourth'] = array(
		   '#type' => 'select',
		   '#title' => t('4th on list'),
		   '#options' => $stack,
		   '#default_value' => variable_get('pdf_download_list_fourth'),
		   '#description' => t('4th on list'),
	   );
	   
		$form ["pdf_download_list_fourth_title"] = array(
	      '#type' => 'textfield',
	      '#title' => t("4th PDF title"),
	      '#default_value' => variable_get("pdf_download_list_fourth_title",""),
	      '#description' => t("4th PDF title"),
	      '#required' => FALSE,
		);
		
		
		
	   $form['pdf_download_list_fifth'] = array(
		   '#type' => 'select',
		   '#title' => t('5th on list'),
		   '#options' => $stack,
		   '#default_value' => variable_get('pdf_download_list_fifth'),
		   '#description' => t('5th on list'),
	   );
	   
		$form ["pdf_download_list_fifth_title"] = array(
	      '#type' => 'textfield',
	      '#title' => t("5th PDF title"),
	      '#default_value' => variable_get("pdf_download_list_fifth_title",""),
	      '#description' => t("5th PDF title"),
	      '#required' => FALSE,
		);
		
		
		
	   
   
	return system_settings_form($form);
}
/**
 * Page callback for /hello.
 */




function pdf_download_list_content(){

	$base_url = $GLOBALS['base_url'];
	
 //$HTML =  '<a href="'.variable_get('pdf_download_list_first').'" class="pdf"><i class="fa fa-download" aria-hidden="true"></i>&nbsp;20. Vested PRSA TV In Endorsement</a>';
  //return $HTML;
  //return '<div class="maincontent" style="margin-top:30px;">test</div>';
 



  $HTML =  '
  <div class="pdf_download_list">
  <h2>'.variable_get('pdf_download_list_popular_title').'</h2>
    <ul class="popularPDFs" style="list-style-type:none;">
    <li style="list-style-type:none;"><i class="fa fa-file-pdf-o" aria-hidden="true"></i><span><a class="top_pdf_link" href="'.variable_get('pdf_download_list_first').'">'.variable_get('pdf_download_list_first_title').'</a></span></li>
	
    <li style="list-style-type:none;"><i class="fa fa-file-pdf-o" aria-hidden="true"></i><span><a class="top_pdf_link" href="'.variable_get('pdf_download_list_second').'">'.variable_get('pdf_download_list_second_title').'</a></span></li>
	
    <li style="list-style-type:none;"><i class="fa fa-file-pdf-o" aria-hidden="true"></i><span><a class="top_pdf_link" href="'.variable_get('pdf_download_list_third').'">'.variable_get('pdf_download_list_third_title').'</a></span></li>
	
    <li style="list-style-type:none;"><i class="fa fa-file-pdf-o" aria-hidden="true"></i><span><a class="top_pdf_link" href="'.variable_get('pdf_download_list_fourth').'">'.variable_get('pdf_download_list_fourth_title').'</a></span></li>
	
    <li style="list-style-type:none;"><i class="fa fa-file-pdf-o" aria-hidden="true"></i><span><a class="top_pdf_link" href="'.variable_get('pdf_download_list_fifth').'">'.variable_get('pdf_download_list_fifth_title').'</a></span></li>
	
    </ul>
  </div>
  
  ';
  return $HTML;


  
}

function pdf_download_list_block_view($delta = '') {
  switch($delta) {
    case 'pdf_download_list':
    $block['subject'] = t('');
    if (user_access('access content')) {
      // Use our custom function to retrieve data
      $result = pdf_download_list_content();
      // No content in the last week

      $block['content'] = $result;
      drupal_add_css(drupal_get_path('module', 'pdf_download_list') . '/css/pdf_download_list.css', array('group' => CSS_DEFAULT));
      drupal_add_js(drupal_get_path('module', 'pdf_download_list') .'/js/document-smart-filter.js');


    }
    return $block;
  }
 }
 