<?php
/**
 * @file
 * A block module that displays the pension calculator.
 */

function online_services_menu() {
  $items = array();
     
  $items['my-online-services'] = array(
    'title' => 'My Online Services Launch Page',
    'page callback' => 'online_services_contents',
     'access arguments' => array('access content'),
	 );
	 return $items;
}


/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */

function online_services_help($path, $arg) {
  switch ($path) {
    case "admin/help#online_services":
      return '<p>' . t("Displays links to nodes created on this date") . '</p>';
      break;
  }
}

function online_services_contents(){ 
	echo '<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Online Services from Irish Life</title>

    <!-- Bootstrap Core CSS -->
    <link href="sites/all/modules/online_services/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="sites/all/modules/online_services/css/one-page-wonder.css" rel="stylesheet">
	<link href="sites/all/modules/online_services/css/animate.css" rel="stylesheet">
	
	<!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
	
	
	<!-- Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn\'t work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
	
	<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-KLB979" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script type="text/javascript">(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':new Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0];var j=d.createElement(s);var dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.src=\'//www.googletagmanager.com/gtm.js?id=\'+i+dl;j.type=\'text/javascript\';j.async=true;f.parentNode.insertBefore(j,f);})(window,document,\'script\',\'dataLayer\',\'GTM-KLB979\');</script>
<!-- End Google Tag Manager -->
	

</head>

<body>

    <!-- Navigation -->
    <nav id="home" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container" id="topMenu">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                
                <a class="navbar-brand" href="#"><img src="https://www.irishlife.ie/onlineApplication/50plus/irishlife-logo.png"></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="rightHeader">
                <ul class="right-menu">
                    <li>
                        <a href="https://twitter.com/IrishLife?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"><i style="color:#1da1f2" class="fa fa-twitter fa-2" aria-hidden="true">@IrishLife</i></a>
                    </li>
                    <li>
                        <a href="https://www.irishlife.ie">back to irishlife.ie</a>
                    </li>
                </ul>
			</div>	
       
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Full Width Image Header -->
    <header class="header-image">
        <div class="headline">
            <div class="container">
			<div class="row">
			 <div class="col-lg-6" id="mainText">
			 <h2>YOU SAID... <br/>WE DID</h2>
			 <h4>Here at Irish Life your feedback is extremely important to us. In our recent customer surveys, you told us logging-in to My Online Services was too difficult..<br/><br/> So now we\'re making it easier for you.</h4>
			 <hr />
			 <!--
			 <h4>All your Irish Life communications in one place</h4>
			 -->
			 <div class="topBtn">
		<h3>WATCH THE VIDEO (1:04)&nbsp;&nbsp;<i class="fa fa-video-camera" aria-hidden="true"></i></h3>
		</div>
		<div class="topBtn2">
		<a style="color:white" target="_blank" href="https://www.irishlife.ie/myonlineservices/"><h3>LOGIN TO MY ONLINE SERVICES&nbsp;&nbsp;<i class="fa fa-sign-in" aria-hidden="true"></i></h3></a>
		</div>
		
			 </div>
			 </div>    
            </div>
        </div>
    </header>
	
	<!-- Buttons 
    <div class="row text-center">
		<div class="col-lg-6">
		<div class="topBtn">
		<h3>WATCH VIDEO</h3>
		</div>
		</div>
		<div class="col-lg-6">
		<div class="topBtn2">
		<h3>LOGIN TO MY ONLINE SERVICES<//h3>
		</div>
		</div>
	</div>
	-->
	
    <!-- Page Content -->
    <div class="container">
	
	 <!--Boxes -->
	<div class="row text-center" style="margin-top:35px;">

            <div class="col-lg-4 col-md-4 col-sm-4 hero-feature">
                <div class="thumbnail">
                    
                    <div class="caption">
					<i class="fa fa-pencil-square-o fa-5x" aria-hidden="true"></i>
                        <h3>GET STARTED</h3>
                        <p>No user ID?<br/>Get started today!</p>
                        <p>
                            <a href="#register" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-4 col-sm-4 hero-feature">
                <div class="thumbnail">
                    
                    <div class="caption">
					<i class="fa fa-question-circle-o fa-5x" aria-hidden="true"></i>
                        <h3>NEED HELP</h3>
                        <p>Contact us, let us know<br/> how we can help.</p>
                        <p>
                            <a href="#help" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-4 col-sm-4 hero-feature">
                <div class="thumbnail">
                    
                    <div class="caption">
					<i class="fa fa-mobile fa-5x" aria-hidden="true"></i>
                        <h3>GET THE APP</h3>
                        <p>Download our app and access<br/> online services on your device!</p>
                        <p>
                            <a href="#app" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

        </div>

        <hr class="featurette-divider-1">

        <!-- First Featurette -->
		<span class="anchor" id="register"></span>
        <div class="featurette">
            <img class="featurette-image img-responsive pull-right-laptop" width="500px" src="sites/all/modules/online_services/css/img/mac-with-image.jpg">
            <h2 class="featurette-heading">GET STARTED WITH
                <span class="text-muted">ONLINE SERVICES</span>
            </h2>
            <p class="lead">All you need is your user id and password to use my online services. <a style="color:#4C5EAB" target="_blank" href="https://www.irishlife.ie/myonlineservices/">Login now &nbsp;&nbsp;<i class="fa fa-sign-in" aria-hidden="true"></i></a><br/><br/> Forgot your password? <br/>If you\'ve used the system before you can request a new one<a target="_blank" style="color:#4C5EAB" href="/myonlineservices/ClientAccount/ForgotPassword1"> here</a>. <br/><br/>Don\'t have a user id?<br/> Call us now on <strong>01 704 1010</strong> and we will get you started.<p>
   
        </div>

        <hr class="featurette-divider">

        <!-- Second Featurette -->
		<span class="anchor" id="help"></span>
        <div class="featurette">
            <!-- <img class="featurette-image img-responsive pull-left" src="sites/all/modules/online_services/css/img/customer-service.jpg"> -->
			<iframe id="video" class="pull-left" src="https://www.youtube.com/embed/videoseries?list=PL7UQwME1y4qlGZrL1jkLZNXkUhDqBfRRa" frameborder="0" allowfullscreen></iframe>
			
            <h2 class="featurette-heading">GET IN TOUCH AND<br/>
                <span class="text-muted">LET US HELP</span>
            </h2>
			<br/>
            <p class="lead">
			View a selection of videos to assist you or contact: 
			<br/>
			<br/>
			<strong>
			Our Customer Service Team
		    </strong>
			<br/>
            Phone: +353 (0)1 704 1010
            <br/>
			<br/>
            <strong>Normal Opening Hours</strong>
			<br/>
            08:00 to 20:00 (Monday - Thursday)
			<br/>
            10:00 to 18:00 (Friday)
			<br/>
            09:00 to 13:00 (Saturday)
            <br/>
			<br/>
            <strong>Switch Board</strong>
            Phone: +353 (0)1 704 2000</p>
        </div>

        <hr class="featurette-divider">

        <!-- Third Featurette -->
		<span class="anchor" id="app"></span>
        <div class="featurette">
            <img class="featurette-image img-responsive pull-right" src="sites/all/modules/online_services/css/img/download-app.jpg">
            <h2 class="featurette-heading">DOWNLOAD MY ONLINE
                <span class="text-muted">SERVICES APP NOW</span>
            </h2>
            <p class="lead">Download the Irish Life my online services App for both tablet and mobile. Available now on both I-Phone and Android.</p>
			<p class="app-icons"><a href="https://itunes.apple.com/ie/app/my-irish-life/id515357744?mt=8" target="_blank"><img src="sites/all/modules/online_services/css/img/app-store.png"><a href="https://play.google.com/store/apps/details?id=com.irishlife.myirishlife " target=_blank"><img src="sites/all/modules/online_services/css/img/google-play.png"></a></p>
        </div>

        <hr class="featurette-divider">

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
				
				<br/>
                    <p>Irish Life Financial Services ltd. is regulated by the Central Bank of Ireland. Irish Life Assurance plc. is regulated by the Central Bank of Ireland.
					<br/>
					<br/>
                    Irish Life Financial Services ltd and Irish Life Assurance plc Registered Office - Lower Abbey Street, PO Box 129, Freepost, Dublin 1. Phone: 01 704 2000, Contact Us
					<br/>
					<br/>
                    Irish Life Financial Services Registered Number 489221. Irish Life Assurance plc Registered Number 152576.
                    In the interest of customer service, we will record and monitor calls. </p>
                </div>
            </div>
        </footer>
		<a href="#home" class="back-to-top">
        <i class="fa fa-arrow-circle-up"></i>
        </a>

    </div>
    <!-- /.container -->
	
	<!-- Scroll JS -->
	<script src="sites/all/modules/online_services/js/scroll.js"></script>
	<script src="sites/all/modules/online_services/js/backtoTop.js"></script>
	

    <!-- jQuery -->
    <script src="sites/all/modules/online_services/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="sites/all/modules/online_services/js/bootstrap.min.js"></script>

</body>

</html>


';

}
